In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df=pd.read_csv("cars.csv")
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [4]:
df["normalized-losses"].replace("?",np.nan,inplace=True)
df["horsepower"].replace("?",np.nan,inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  164 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         203 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [6]:
from sklearn.impute import SimpleImputer

In [7]:
si=SimpleImputer(missing_values=np.nan,strategy="mean")

In [8]:
df[["normalized-losses","horsepower"]]=si.fit_transform(df[["normalized-losses","horsepower"]])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    float64
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(4), int64(5), object(6)
memory usage: 24.1+ KB


In [10]:
catcol=df.select_dtypes(object).columns

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
oe=OrdinalEncoder()
df[catcol]=oe.fit_transform(df[catcol])

In [14]:
df.head()

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0          3              122.0   0.0        1.0         0.0           2.0   
1          3              122.0   0.0        1.0         0.0           2.0   
2          1              122.0   0.0        1.0         2.0           2.0   
3          2              164.0   1.0        1.0         3.0           1.0   
4          2              164.0   1.0        1.0         3.0           0.0   

   engine-location  width  height  engine-type  engine-size  horsepower  \
0              0.0   64.1    48.8          0.0          130       111.0   
1              0.0   64.1    48.8          0.0          130       111.0   
2              0.0   65.5    52.4          5.0          152       154.0   
3              0.0   66.2    54.3          3.0          109       102.0   
4              0.0   66.4    54.3          3.0          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

In [15]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [16]:
x.ndim

2

In [17]:
y.ndim

1

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
model=LinearRegression()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)

In [22]:
from sklearn.metrics import r2_score

In [23]:
print(r2_score(ytest,ypred))

0.7965566780397382


In [24]:
train=model.score(xtrain,ytrain)
test=model.score(xtest,ytest)

print(train)
print(test)

0.8504573774895473
0.7965566780397382


In [24]:
#as training score is higher than testing score , we can say our model is overfitted
#low bias high variance
#high train score, low testing score

In [25]:
model.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

In [26]:
model.intercept_

-65022.7698599568

In [27]:
from sklearn.linear_model import Ridge,Lasso

In [46]:
l2=Ridge(alpha=10)
l2.fit(xtrain,ytrain)
ypred=l2.predict(xtest)

In [47]:
train=l2.score(xtrain,ytrain)
test=l2.score(xtest,ytest)

print(train)
print(test)

0.8109538582620315
0.8150222867376529


In [32]:
model.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

In [33]:
model.intercept_

-65022.7698599568

In [37]:
l1=Lasso(alpha=10)
l1.fit(xtrain,ytrain)
ypred=l1.predict(xtest)

In [38]:
train=l1.score(xtrain,ytrain)
test=l1.score(xtest,ytest)

print(train)
print(test)

0.8504573774895473
0.7965566780397382


In [36]:
model.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

In [39]:
model.intercept_

-65022.7698599568

## Hyperparameter tunning

In [40]:
for i in range(150,200):
    l1=Lasso(alpha=i)
    l1.fit(xtrain,ytrain)
    train=l1.score(xtrain,ytrain)
    test=l1.score(xtest,ytest)
    print(f"{i} {train} {test}")

150 0.8212288879856346 0.8124969899539802
151 0.8208421468238059 0.8125456274822552
152 0.8204526518423789 0.8125934728624999
153 0.8200607762157638 0.8126404383406128
154 0.8196661304388357 0.812686613158391
155 0.8192691148773522 0.8127319078642978
156 0.8188695301369726 0.8127763675886548
157 0.8184671715223708 0.8128200339758357
158 0.818062449862035 0.8128628223230777
159 0.8176549464501084 0.8129048166168777
160 0.8172450881050914 0.8129459336049878
161 0.8168324400154192 0.8129862557319262
162 0.8164174452457785 0.8130257013815374
163 0.8159998820785823 0.8130643120104756
164 0.8155795285150103 0.8131021244780069
165 0.8151568303042497 0.8131390636923393
166 0.8147313271293923 0.8131752048184053
167 0.8143034914835354 0.8132104730535141
168 0.8138728445987574 0.8132449418027805
169 0.8134398734696936 0.8132785388258218
170 0.8130040832573873 0.8133113351310719
171 0.8125659771958964 0.8133432609587987
172 0.8121250442517013 0.8133743847411005
173 0.8116818034536712 0.81340463945

In [43]:
l1=Lasso(alpha=169)
l1.fit(xtrain,ytrain)
ypred=l1.predict(xtest)

In [48]:
train=l1.score(xtrain,ytrain)
test=l1.score(xtest,ytest)

print(train)
print(test)

0.8134398734696936
0.8132785388258218


In [49]:
l1.coef_

array([ 4.69984023e+00,  1.99632535e+00, -1.72221126e+02, -0.00000000e+00,
       -3.68828572e+02,  1.23866762e+03,  4.35113307e+03,  4.02198115e+02,
        4.53320466e+02,  3.01054481e+02,  1.13016944e+02,  1.01237908e+01,
        8.18884778e+01, -1.71406319e+02])

In [50]:
l1.intercept_

-49650.88318694639